trigger: none

# Schedule to run overnight
schedules:
- cron: "0 20 * * *"
  displayName: Daily overnight build
  branches:
    include:
    - develop
 
# Include shared variables
variables:
- template: shared-variables.yml

stages:
- template: shared-build-and-test-stage.yml
  runTests: variables['RunTests']

# Try to complete the corresponding pull request if
# this is triggered by one.    
- template: shared-auto-complete-pr-stage.yml@ciTemplates
  parameters:
    stageDependencies: [Build_and_Test]