trigger: none

# Schedule to run overnight
schedules:
- cron: "0 20 * * *"
  displayName: Daily overnight build
  branches:
    include:
    - develop

# Add the common-ci git repo as a resource to access common templates.
resources:
  repositories:
  - repository: ciTemplates # Id of the repository used to reference to in this script
    type: git
    name: common-ci # Name of the actual repository
    
# Include shared variables
variables:
- template: shared-variables.yml@ciTemplates
- group: CIAutomation # Required to access CI variables

stages:
- template: shared-build-and-test-stage.yml
  parameters:
    runTests: variables['RunTests']
    windowsImage: ${{ variables.windowsImage }}
    linuxImage: ${{ variables.linuxImage }}
    macImage: ${{ variables.macImage }}

# Try to complete the corresponding pull request if
# this is triggered by one.    
- template: shared-auto-complete-pr-stage.yml@ciTemplates
  parameters:
    stageDependencies: [Linux,MacOS,Windows]